/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AkSideDraw {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLAkSideDrawElement extends Components.AkSideDraw, HTMLStencilElement {
    }
    var HTMLAkSideDrawElement: {
        prototype: HTMLAkSideDrawElement;
        new (): HTMLAkSideDrawElement;
    };
    interface HTMLElementTagNameMap {
        "ak-side-draw": HTMLAkSideDrawElement;
    }
}
declare namespace LocalJSX {
    interface AkSideDraw {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "ak-side-draw": AkSideDraw;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ak-side-draw": LocalJSX.AkSideDraw & JSXBase.HTMLAttributes<HTMLAkSideDrawElement>;
        }
    }
}
